### ISSUE TITLE
Manjkajoc ER diagram

### ISSUE THREAD

**Issue by PirnovarA** [1marcelspehonja/Sport#1]
Pozdravljeni. Manjka vam ER diagram. Sicer se ne tocno spomnim predstavitve, a predvidevam, da ste ga takrat imeli? Ne priganjam, samo opozorim, da bi bilo dobro, da ga imate (kot osnovni oris projekta).

**Comment by 1marcelspehonja** [comment]
Pozdravljeni!
Hvala za opozorilo. ER diagram smo imeli na predstavitvi, vendar smo ga
pozabili dodati na repozitorij. Sedaj smo ga dodali.
Lp, Marcel Špehonja

V V sre., 22. apr. 2020 ob 23:25 je oseba PirnovarA <
notifications@github.com> napisala:

**Comment by PirnovarA** [comment]
Super!
Lp, Andraz
