### ISSUE TITLE
Urejanje tabele

### ISSUE THREAD

**Issue by dePauk** [1marcelspehonja/Sport#3]
Pozdravljeni!
Poskušam dodati kodo za urejanje sponzorjev v tabeli `ekipe`, vendar sem dobil že mnogo različnih napak, nikoli pa ni delovala. Koda sicer še ne bi dejansko spremenila podatkov v tabeli, vendar bi rad, da v tej fazi ob pritisku na gumb 'Uredi' v tabeli na _/16/ekipe_ vsaj vrže na delujočo stran, _/ekipe/uredi/<ID>_ , kjer bi potem lahko uredil podatke o sponzorju za posamezno ekipo. Iz error-ja, ki ga program vrže, je razvidno, da se nekje primerja string in integer (_HINT:  No operator matches the given name and argument type(s)_ )., toda ne vem, v čem je problem .

Koda se nahaja v:
`ekipe-edit.html`, `ekipe.html` -> na dnu tabele, in `sport.py` -> @get('/ekipe/uredi/<ID>')

**Comment by dePauk** [comment]
Kolega je ugotovil, kaj je bilo narobe, tako da sedaj deluje.

**Comment by dePauk** [comment]
Pozdravljeni!

Po novih commitih kot kaže ne deluje več, saj preusmeri na neko povsem drugo stran ("NBA menedžerji") namesto na to, kar bi moralo biti na /.../ekipe/uredi/ID , kljub temu da je link enak kot prej. Napaka je najbrž zaradi {{leto}} ali česa podobnega v linkih, vendar sem poskusil vse možne kombinacije in nobena ni delovala. Ne vem tudi, po katerem commitu točno se je to zgodilo.

**Comment by dePauk** [comment]
Sedaj sicer deluje, vendar sem si pomagal z if-stavkom in me zanima, ali je tako OK?

**Comment by jaanos** [comment]
Koda naj ne bo odvisna od vsebine baze - sezono raje dobite s poizvedbo iz baze. Lahko naredite še en `SELECT`, lahko si pa pomagate z `RETURNING`:
```python
cur.execute("UPDATE ekipe SET Sponzor_na_dresu = %s WHERE ID = %s RETURNING sezona", (Sponzor_na_dresu, ID))
sezona, = cur.fetchone()
```
Mimogrede, opažam, da imate v bazi nize *NA*, kjer nimate podatkov - namesto tega imejte raje vrednost `NULL` (seveda bo potrebno pri stolpcih, kjer se to lahko zgodi, odstraniti lastnost `NOT NULL`).
